/*
 * @file    TrainRouting.c
 * @brief   Contains functions used to guide a train from its current position
 *          to its destination
 * @author  Liam JA MacDonald
 * @author  Patrick Wells
 * @date    9-Dec-2019 (created)
 * @date
 */
#include "TrainRouting.h"

/* Container of train state(s) */
struct TrainState States[NUM_TRAINS] = {DEFAULT_SPEED, DEFAULT_DESTINATION};

/* Routing table used to instruct a train how to go from one location to another */
static const struct RoutingTableEntry RoutingTable[NUM_SENSORS][NUM_SENSORS] =
{
/*From      TO  1                                        2                                   3                                   4                                   5                                   6                                   7                                   8                                  9                                  10                                  11                                  12                                  13                                  14                                  15                                  16                                   17                                  18                                 19                                  20                                   21                                  22                                 23                                  24               */
/* 1 */{{DIR_CW, NO_SWITCH, NO_SWITCH, 1},   {DIR_CCW, 6, SW_STRAIGHT, 0},       {DIR_CCW, 6, SW_STRAIGHT, 0},       {DIR_CCW, 6, SW_STRAIGHT, 0},       {DIR_CCW, 6, SW_STRAIGHT, 0},       {DIR_CCW, 6, SW_STRAIGHT, 0},       {DIR_CCW, 6, SW_STRAIGHT, 0},       {DIR_CCW, 6, SW_STRAIGHT, 0},       {DIR_CW, 1, SW_STRAIGHT, 0},        {DIR_CW, 1, SW_STRAIGHT, 0},        {DIR_CW, 1, SW_STRAIGHT, 0},        {DIR_CW, 1, SW_STRAIGHT, 0},        {DIR_CW, 1, SW_STRAIGHT, 0},        {DIR_CW, NO_SWITCH, NO_SWITCH, 0},  {DIR_CW, NO_SWITCH, NO_SWITCH, 0},  {DIR_CW, NO_SWITCH, NO_SWITCH, 0},  {DIR_CCW, 6, SW_DIVERGED, 0},       {DIR_CCW, 6, SW_DIVERGED, 0},       {DIR_CW, 1, SW_DIVERGED, 0},        {DIR_CW, 1, SW_DIVERGED, 0},        {DIR_CCW, 6, SW_STRAIGHT, 0},       {DIR_CCW, 6, SW_STRAIGHT, 0},       {DIR_CW, 1, SW_STRAIGHT, 0},        {DIR_CW, 1, SW_STRAIGHT, 0}},
/* 2 */{{DIR_CW, 6, SW_STRAIGHT, 0},         {DIR_CW, NO_SWITCH, NO_SWITCH, 1},  {DIR_CCW, NO_SWITCH, NO_SWITCH, 0}, {DIR_CCW, 5, SW_STRAIGHT, 0},       {DIR_CCW, 5, SW_STRAIGHT, 0},       {DIR_CCW, 5, SW_STRAIGHT, 0},       {DIR_CCW, 5, SW_STRAIGHT, 0},       {DIR_CCW, 5, SW_STRAIGHT, 0},       {DIR_CCW, 5, SW_STRAIGHT, 0},       {DIR_CW, 6, SW_STRAIGHT, 0},        {DIR_CW, 6, SW_STRAIGHT, 0},        {DIR_CW, 6, SW_STRAIGHT, 0},        {DIR_CW, 6, SW_STRAIGHT, 0},        {DIR_CW, 6, SW_STRAIGHT, 0},        {DIR_CW, 6, SW_STRAIGHT, 0},        {DIR_CW, 6, SW_STRAIGHT, 0},        {DIR_CW, 6, SW_STRAIGHT, 0},        {DIR_CW, 6, SW_STRAIGHT, 0},        {DIR_CCW, 5, SW_STRAIGHT, 0},       {DIR_CW, 6, SW_STRAIGHT, 0},        {DIR_CCW, 5, SW_DIVERGED, 0},       {DIR_CCW, 5, SW_DIVERGED, 0},       {DIR_CW, 6, SW_STRAIGHT, 0},        {DIR_CW, 6, SW_STRAIGHT, 0}},
/* 3 */{{DIR_CW, 6, SW_STRAIGHT, 0},         {DIR_CW, NO_SWITCH, NO_SWITCH, 0},  {DIR_CW, NO_SWITCH, NO_SWITCH, 1},  {DIR_CCW, 5, SW_STRAIGHT, 0},       {DIR_CCW, 5, SW_STRAIGHT, 0},       {DIR_CCW, 5, SW_STRAIGHT, 0},       {DIR_CCW, 5, SW_STRAIGHT, 0},       {DIR_CCW, 5, SW_STRAIGHT, 0},       {DIR_CCW, 5, SW_STRAIGHT, 0},       {DIR_CCW, 5, SW_STRAIGHT, 0},       {DIR_CW, 6, SW_STRAIGHT, 0},        {DIR_CW, 6, SW_STRAIGHT, 0},        {DIR_CW, 6, SW_STRAIGHT, 0},        {DIR_CW, 6, SW_STRAIGHT, 0},        {DIR_CW, 6, SW_STRAIGHT, 0},        {DIR_CW, 6, SW_STRAIGHT, 0},        {DIR_CW, 6, SW_STRAIGHT, 0},        {DIR_CW, 6, SW_STRAIGHT, 0},        {DIR_CCW, 5, SW_STRAIGHT, 0},       {DIR_CW, 6, SW_STRAIGHT, 0},        {DIR_CCW, 5, SW_DIVERGED, 0},       {DIR_CCW, 5, SW_DIVERGED, 0},       {DIR_CW, 6, SW_STRAIGHT, 0},        {DIR_CW, 6, SW_STRAIGHT, 0}},
/* 4 */{{DIR_CW, 5, SW_STRAIGHT, 0},         {DIR_CW, 5, SW_STRAIGHT, 0},        {DIR_CW, 5, SW_STRAIGHT, 0},        {DIR_CW, NO_SWITCH, NO_SWITCH, 1},  {DIR_CCW, NO_SWITCH, NO_SWITCH, 0}, {DIR_CCW, 4, SW_STRAIGHT, 0},       {DIR_CCW, 4, SW_STRAIGHT, 0},       {DIR_CCW, 4, SW_STRAIGHT, 0},       {DIR_CCW, 4, SW_STRAIGHT, 0},       {DIR_CCW, 4, SW_STRAIGHT, 0},       {DIR_CCW, 4, SW_STRAIGHT, 0},       {DIR_CW, 5, SW_STRAIGHT, 0},        {DIR_CW, 5, SW_STRAIGHT, 0},        {DIR_CW, 5, SW_STRAIGHT, 0},        {DIR_CW, 5, SW_STRAIGHT, 0},        {DIR_CW, 5, SW_STRAIGHT, 0},        {DIR_CCW, 4, SW_STRAIGHT, 0},       {DIR_CCW, 4, SW_STRAIGHT, 0},       {DIR_CCW, 4, SW_STRAIGHT, 0},       {DIR_CCW, 4, SW_STRAIGHT, 0},       {DIR_CW, 5, SW_STRAIGHT, 0},        {DIR_CW, 5, SW_STRAIGHT, 0},        {DIR_CCW, 4, SW_STRAIGHT, 0},       {DIR_CCW, 4, SW_STRAIGHT, 0}},
/* 5 */{{DIR_CW, 5, SW_STRAIGHT, 0},         {DIR_CW, 5, SW_STRAIGHT, 0},        {DIR_CW, 5, SW_STRAIGHT, 0},        {DIR_CW, NO_SWITCH, NO_SWITCH, 0},  {DIR_CW, NO_SWITCH, NO_SWITCH, 1},  {DIR_CCW, 4, SW_STRAIGHT, 0},       {DIR_CCW, 4, SW_STRAIGHT, 0},       {DIR_CCW, 4, SW_STRAIGHT, 0},       {DIR_CCW, 4, SW_STRAIGHT, 0},       {DIR_CCW, 4, SW_STRAIGHT, 0},       {DIR_CCW, 4, SW_STRAIGHT, 0},       {DIR_CCW, 4, SW_STRAIGHT, 0},       {DIR_CW, 5, SW_STRAIGHT, 0},        {DIR_CW, 5, SW_STRAIGHT, 0},        {DIR_CW, 5, SW_STRAIGHT, 0},        {DIR_CW, 5, SW_STRAIGHT, 0},        {DIR_CCW, 4, SW_STRAIGHT, 0},       {DIR_CCW, 4, SW_STRAIGHT, 0},       {DIR_CCW, 4, SW_STRAIGHT, 0},       {DIR_CCW, 4, SW_STRAIGHT, 0},       {DIR_CW, 5, SW_STRAIGHT, 0},        {DIR_CW, 5, SW_STRAIGHT, 0},        {DIR_CCW, 4, SW_STRAIGHT, 0},       {DIR_CCW, 4, SW_STRAIGHT, 0}},
/* 6 */{{DIR_CW, 4, SW_STRAIGHT, 0},         {DIR_CW, 4, SW_STRAIGHT, 0},        {DIR_CW, 4, SW_STRAIGHT, 0},        {DIR_CW, 4, SW_STRAIGHT, 0},        {DIR_CW, 4, SW_STRAIGHT, 0},        {DIR_CW, NO_SWITCH, NO_SWITCH, 1},  {DIR_CCW, NO_SWITCH, NO_SWITCH, 0}, {DIR_CCW, NO_SWITCH, NO_SWITCH, 0}, {DIR_CCW, NO_SWITCH, NO_SWITCH, 0}, {DIR_CCW, 3, SW_STRAIGHT, 0},       {DIR_CCW, 3, SW_STRAIGHT, 0},       {DIR_CCW, 3, SW_STRAIGHT, 0},       {DIR_CCW, 3, SW_STRAIGHT, 0},       {DIR_CW, 4, SW_STRAIGHT, 0},        {DIR_CW, 4, SW_STRAIGHT, 0},        {DIR_CW, 4, SW_STRAIGHT, 0},        {DIR_CW, 4, SW_DIVERGED, 0},        {DIR_CW, 4, SW_DIVERGED, 0},        {DIR_CCW, 3, SW_DIVERGED, 0},       {DIR_CCW, 3, SW_DIVERGED, 0},       {DIR_CW, 4, SW_STRAIGHT, 0},        {DIR_CW, 4, SW_STRAIGHT, 0},        {DIR_CCW, 3, SW_STRAIGHT, 0},       {DIR_CCW, 3, SW_STRAIGHT, 0}},
/* 7 */{{DIR_CW, 4, SW_STRAIGHT, 0},         {DIR_CW, 4, SW_STRAIGHT, 0},        {DIR_CW, 4, SW_STRAIGHT, 0},        {DIR_CW, 4, SW_STRAIGHT, 0},        {DIR_CW, 4, SW_STRAIGHT, 0},        {DIR_CW, NO_SWITCH, NO_SWITCH, 0},  {DIR_CW, NO_SWITCH, NO_SWITCH, 1},  {DIR_CCW, NO_SWITCH, NO_SWITCH, 0}, {DIR_CCW, NO_SWITCH, NO_SWITCH, 0}, {DIR_CCW, 3, SW_STRAIGHT, 0},       {DIR_CCW, 3, SW_STRAIGHT, 0},       {DIR_CCW, 3, SW_STRAIGHT, 0},       {DIR_CCW, 3, SW_STRAIGHT, 0},       {DIR_CCW, 3, SW_STRAIGHT, 0},       {DIR_CW, 4, SW_STRAIGHT, 0},        {DIR_CW, 4, SW_STRAIGHT, 0},        {DIR_CW, 4, SW_DIVERGED, 0},        {DIR_CW, 4, SW_DIVERGED, 0},        {DIR_CCW, 3, SW_DIVERGED, 0},       {DIR_CCW, 3, SW_DIVERGED, 0},       {DIR_CW, 4, SW_STRAIGHT, 0},        {DIR_CW, 4, SW_STRAIGHT, 0},        {DIR_CCW, 3, SW_STRAIGHT, 0},       {DIR_CCW, 3, SW_STRAIGHT, 0}},
/* 8 */{{DIR_CW, 4, SW_STRAIGHT, 0},         {DIR_CW, 4, SW_STRAIGHT, 0},        {DIR_CW, 4, SW_STRAIGHT, 0},        {DIR_CW, 4, SW_STRAIGHT, 0},        {DIR_CW, 4, SW_STRAIGHT, 0},        {DIR_CW, NO_SWITCH, NO_SWITCH, 0},  {DIR_CW, NO_SWITCH, NO_SWITCH, 0},  {DIR_CW, NO_SWITCH, NO_SWITCH, 1},  {DIR_CCW, NO_SWITCH, NO_SWITCH, 0}, {DIR_CCW, 3, SW_STRAIGHT, 0},       {DIR_CCW, 3, SW_STRAIGHT, 0},       {DIR_CCW, 3, SW_STRAIGHT, 0},       {DIR_CCW, 3, SW_STRAIGHT, 0},       {DIR_CCW, 3, SW_STRAIGHT, 0},       {DIR_CCW, 3, SW_STRAIGHT, 0},       {DIR_CW, 4, SW_STRAIGHT, 0},        {DIR_CW, 4, SW_DIVERGED, 0},        {DIR_CW, 4, SW_DIVERGED, 0},        {DIR_CCW, 3, SW_DIVERGED, 0},       {DIR_CCW, 3, SW_DIVERGED, 0},       {DIR_CW, 4, SW_STRAIGHT, 0},        {DIR_CW, 4, SW_STRAIGHT, 0},        {DIR_CCW, 3, SW_STRAIGHT, 0},       {DIR_CCW, 3, SW_STRAIGHT, 0}},
/* 9 */{{DIR_CW, 4, SW_STRAIGHT, 0},         {DIR_CW, 4, SW_STRAIGHT, 0},        {DIR_CW, 4, SW_STRAIGHT, 0},        {DIR_CW, 4, SW_STRAIGHT, 0},        {DIR_CW, 4, SW_STRAIGHT, 0},        {DIR_CW, NO_SWITCH, NO_SWITCH, 0},  {DIR_CW, NO_SWITCH, NO_SWITCH, 0},  {DIR_CW, NO_SWITCH, NO_SWITCH, 0},  {DIR_CW, NO_SWITCH, NO_SWITCH, 1},  {DIR_CCW, 3, SW_STRAIGHT, 0},       {DIR_CCW, 3, SW_STRAIGHT, 0},       {DIR_CCW, 3, SW_STRAIGHT, 0},       {DIR_CCW, 3, SW_STRAIGHT, 0},       {DIR_CCW, 3, SW_STRAIGHT, 0},       {DIR_CCW, 3, SW_STRAIGHT, 0},       {DIR_CCW, 3, SW_STRAIGHT, 0},       {DIR_CW, 4, SW_DIVERGED, 0},        {DIR_CW, 4, SW_DIVERGED, 0},        {DIR_CCW, 3, SW_DIVERGED, 0},       {DIR_CCW, 3, SW_DIVERGED, 0},       {DIR_CW, 4, SW_STRAIGHT, 0},        {DIR_CW, 4, SW_STRAIGHT, 0},        {DIR_CCW, 3, SW_STRAIGHT, 0},       {DIR_CCW, 3, SW_STRAIGHT, 0}},
/* 10*/{{DIR_CCW, 2, SW_STRAIGHT, 0},        {DIR_CW, 3, SW_STRAIGHT, 0},        {DIR_CW, 3, SW_STRAIGHT, 0},        {DIR_CW, 3, SW_STRAIGHT, 0},        {DIR_CW, 3, SW_STRAIGHT, 0},        {DIR_CW, 3, SW_STRAIGHT, 0},        {DIR_CW, 3, SW_STRAIGHT, 0},        {DIR_CW, 3, SW_STRAIGHT, 0},        {DIR_CW, 3, SW_STRAIGHT, 0},        {DIR_CW, NO_SWITCH, NO_SWITCH, 1},  {DIR_CCW, NO_SWITCH, NO_SWITCH, 0}, {DIR_CCW, 2, SW_STRAIGHT, 0},       {DIR_CCW, 2, SW_STRAIGHT, 0},       {DIR_CCW, 2, SW_STRAIGHT, 0},       {DIR_CCW, 2, SW_STRAIGHT, 0},       {DIR_CCW, 2, SW_STRAIGHT, 0},       {DIR_CCW, 2, SW_STRAIGHT, 0},       {DIR_CCW, 2, SW_STRAIGHT, 0},       {DIR_CW, 3, SW_STRAIGHT, 0},        {DIR_CW, 3, SW_STRAIGHT, 0},        {DIR_CCW, 2, SW_STRAIGHT, 0},       {DIR_CCW, 2, SW_STRAIGHT, 0},       {DIR_CCW, 2, SW_DIVERGED, 0},       {DIR_CCW, 2, SW_DIVERGED, 0}},
/* 11*/{{DIR_CCW, 2, SW_STRAIGHT, 0},        {DIR_CCW, 2, SW_STRAIGHT, 0},       {DIR_CW, 3, SW_STRAIGHT, 0},        {DIR_CW, 3, SW_STRAIGHT, 0},        {DIR_CW, 3, SW_STRAIGHT, 0},        {DIR_CW, 3, SW_STRAIGHT, 0},        {DIR_CW, 3, SW_STRAIGHT, 0},        {DIR_CW, 3, SW_STRAIGHT, 0},        {DIR_CW, 3, SW_STRAIGHT, 0},        {DIR_CW, NO_SWITCH, NO_SWITCH, 0},  {DIR_CW, NO_SWITCH, NO_SWITCH, 1},  {DIR_CCW, 2, SW_STRAIGHT, 0},       {DIR_CCW, 2, SW_STRAIGHT, 0},       {DIR_CCW, 2, SW_STRAIGHT, 0},       {DIR_CCW, 2, SW_STRAIGHT, 0},       {DIR_CCW, 2, SW_STRAIGHT, 0},       {DIR_CCW, 2, SW_STRAIGHT, 0},       {DIR_CCW, 2, SW_STRAIGHT, 0},       {DIR_CW, 3, SW_STRAIGHT, 0},        {DIR_CW, 3, SW_STRAIGHT, 0},        {DIR_CW, 3, SW_STRAIGHT, 0},        {DIR_CW, 3, SW_STRAIGHT, 0},        {DIR_CCW, 2, SW_DIVERGED, 0},       {DIR_CCW, 2, SW_DIVERGED, 0}},
/* 12*/{{DIR_CCW, 1, SW_STRAIGHT, 0},        {DIR_CCW, 1, SW_STRAIGHT, 0},       {DIR_CCW, 1, SW_STRAIGHT, 0},       {DIR_CW, 2, SW_STRAIGHT, 0},        {DIR_CW, 2, SW_STRAIGHT, 0},        {DIR_CW, 2, SW_STRAIGHT, 0},        {DIR_CW, 2, SW_STRAIGHT, 0},        {DIR_CW, 2, SW_STRAIGHT, 0},        {DIR_CW, 2, SW_STRAIGHT, 0},        {DIR_CW, 2, SW_STRAIGHT, 0},        {DIR_CW, 2, SW_STRAIGHT, 0},        {DIR_CW, NO_SWITCH, NO_SWITCH, 1},  {DIR_CCW, NO_SWITCH, NO_SWITCH, 0}, {DIR_CCW, 1, SW_STRAIGHT, 0},       {DIR_CCW, 1, SW_STRAIGHT, 0},       {DIR_CCW, 1, SW_STRAIGHT, 0},       {DIR_CCW, 1, SW_STRAIGHT, 0},       {DIR_CCW, 1, SW_STRAIGHT, 0},       {DIR_CCW, 1, SW_STRAIGHT, 0},       {DIR_CCW, 1, SW_STRAIGHT, 0},       {DIR_CCW, 1, SW_STRAIGHT, 0},       {DIR_CCW, 1, SW_STRAIGHT, 0},       {DIR_CW, 2, SW_STRAIGHT, 0},        {DIR_CW, 2, SW_STRAIGHT, 0}},
/* 13*/{{DIR_CCW, 1, SW_STRAIGHT, 0},        {DIR_CCW, 1, SW_STRAIGHT, 0},       {DIR_CCW, 1, SW_STRAIGHT, 0},       {DIR_CCW, 1, SW_STRAIGHT, 0},       {DIR_CW, 2, SW_STRAIGHT, 0},        {DIR_CW, 2, SW_STRAIGHT, 0},        {DIR_CW, 2, SW_STRAIGHT, 0},        {DIR_CW, 2, SW_STRAIGHT, 0},        {DIR_CW, 2, SW_STRAIGHT, 0},        {DIR_CW, 2, SW_STRAIGHT, 0},        {DIR_CW, 2, SW_STRAIGHT, 0},        {DIR_CW, NO_SWITCH, NO_SWITCH, 0},  {DIR_CW, NO_SWITCH, NO_SWITCH, 1},  {DIR_CCW, 1, SW_STRAIGHT, 0},       {DIR_CCW, 1, SW_STRAIGHT, 0},       {DIR_CCW, 1, SW_STRAIGHT, 0},       {DIR_CCW, 1, SW_STRAIGHT, 0},       {DIR_CCW, 1, SW_STRAIGHT, 0},       {DIR_CCW, 1, SW_STRAIGHT, 0},       {DIR_CCW, 1, SW_STRAIGHT, 0},       {DIR_CCW, 1, SW_STRAIGHT, 0},       {DIR_CCW, 1, SW_STRAIGHT, 0},       {DIR_CW, 2, SW_STRAIGHT, 0},        {DIR_CW, 2, SW_STRAIGHT, 0}},
/* 14*/{{DIR_CCW, NO_SWITCH, NO_SWITCH, 0},  {DIR_CCW, 6, SW_STRAIGHT, 0},       {DIR_CCW, 6, SW_STRAIGHT, 0},       {DIR_CCW, 6, SW_STRAIGHT, 0},       {DIR_CCW, 6, SW_STRAIGHT, 0},       {DIR_CW, 1, SW_STRAIGHT, 0},        {DIR_CW, 1, SW_STRAIGHT, 0},        {DIR_CW, 1, SW_STRAIGHT, 0},        {DIR_CW, 1, SW_STRAIGHT, 0},        {DIR_CW, 1, SW_STRAIGHT, 0},        {DIR_CW, 1, SW_STRAIGHT, 0},        {DIR_CW, 1, SW_STRAIGHT, 0},        {DIR_CW, 1, SW_STRAIGHT, 0},        {DIR_CW, NO_SWITCH, NO_SWITCH, 1},  {DIR_CCW, NO_SWITCH, NO_SWITCH, 0}, {DIR_CCW, NO_SWITCH, NO_SWITCH, 0}, {DIR_CCW, 6, SW_DIVERGED, 0},       {DIR_CCW, 6, SW_DIVERGED, 0},       {DIR_CW, 1, SW_DIVERGED, 0},        {DIR_CW, 1, SW_DIVERGED, 0},        {DIR_CCW, 6, SW_STRAIGHT, 0},       {DIR_CCW, 6, SW_STRAIGHT, 0},       {DIR_CW, 1, SW_STRAIGHT, 0},        {DIR_CW, 1, SW_STRAIGHT, 0}},
/* 15*/{{DIR_CCW, NO_SWITCH, NO_SWITCH, 0},  {DIR_CCW, 6, SW_STRAIGHT, 0},       {DIR_CCW, 6, SW_STRAIGHT, 0},       {DIR_CCW, 6, SW_STRAIGHT, 0},       {DIR_CCW, 6, SW_STRAIGHT, 0},       {DIR_CCW, 6, SW_STRAIGHT, 0},       {DIR_CW, 1, SW_STRAIGHT, 0},        {DIR_CW, 1, SW_STRAIGHT, 0},        {DIR_CW, 1, SW_STRAIGHT, 0},        {DIR_CW, 1, SW_STRAIGHT, 0},        {DIR_CW, 1, SW_STRAIGHT, 0},        {DIR_CW, 1, SW_STRAIGHT, 0},        {DIR_CW, 1, SW_STRAIGHT, 0},        {DIR_CW, NO_SWITCH, NO_SWITCH, 0},  {DIR_CW, NO_SWITCH, NO_SWITCH, 1},  {DIR_CCW, NO_SWITCH, NO_SWITCH, 0}, {DIR_CCW, 6, SW_DIVERGED, 0},       {DIR_CCW, 6, SW_DIVERGED, 0},       {DIR_CW, 1, SW_DIVERGED, 0},        {DIR_CW, 1, SW_DIVERGED, 0},        {DIR_CCW, 6, SW_STRAIGHT, 0},       {DIR_CCW, 6, SW_STRAIGHT, 0},       {DIR_CW, 1, SW_STRAIGHT, 0},        {DIR_CW, 1, SW_STRAIGHT, 0}},
/* 16*/{{DIR_CCW, NO_SWITCH, NO_SWITCH, 0},  {DIR_CCW, 6, SW_STRAIGHT, 0},       {DIR_CCW, 6, SW_STRAIGHT, 0},       {DIR_CCW, 6, SW_STRAIGHT, 0},       {DIR_CCW, 6, SW_STRAIGHT, 0},       {DIR_CCW, 6, SW_STRAIGHT, 0},       {DIR_CCW, 6, SW_STRAIGHT, 0},       {DIR_CW, 1, SW_STRAIGHT, 0},        {DIR_CW, 1, SW_STRAIGHT, 0},        {DIR_CW, 1, SW_STRAIGHT, 0},        {DIR_CW, 1, SW_STRAIGHT, 0},        {DIR_CW, 1, SW_STRAIGHT, 0},        {DIR_CW, 1, SW_STRAIGHT, 0},        {DIR_CW, NO_SWITCH, NO_SWITCH, 0},  {DIR_CW, NO_SWITCH, NO_SWITCH, 0},  {DIR_CW, NO_SWITCH, NO_SWITCH, 1},  {DIR_CCW, 6, SW_DIVERGED, 0},       {DIR_CCW, 6, SW_DIVERGED, 0},       {DIR_CW, 1, SW_DIVERGED, 0},        {DIR_CW, 1, SW_DIVERGED, 0},        {DIR_CCW, 6, SW_STRAIGHT, 0},       {DIR_CCW, 6, SW_STRAIGHT, 0},       {DIR_CW, 1, SW_STRAIGHT, 0},        {DIR_CW, 1, SW_STRAIGHT, 0}},
/* 17*/{{DIR_CW, 6, SW_DIVERGED, 0},         {DIR_CW, 6, SW_DIVERGED, 0},        {DIR_CW, 6, SW_DIVERGED, 0},        {DIR_CCW, 4, SW_DIVERGED, 0},       {DIR_CCW, 4, SW_DIVERGED, 0},       {DIR_CCW, 4, SW_DIVERGED, 0},       {DIR_CCW, 4, SW_DIVERGED, 0},       {DIR_CCW, 4, SW_DIVERGED, 0},       {DIR_CCW, 4, SW_DIVERGED, 0},       {DIR_CCW, 4, SW_DIVERGED, 0},       {DIR_CCW, 4, SW_DIVERGED, 0},       {DIR_CW, 6, SW_DIVERGED, 0},        {DIR_CW, 6, SW_DIVERGED, 0},        {DIR_CW, 6, SW_DIVERGED, 0},        {DIR_CW, 6, SW_DIVERGED, 0},        {DIR_CW, 6, SW_DIVERGED, 0},        {DIR_CW, NO_SWITCH, NO_SWITCH, 1},  {DIR_CCW, NO_SWITCH, NO_SWITCH, 0}, {DIR_CCW, 4, SW_DIVERGED, 0},       {DIR_CW, 6, SW_DIVERGED, 0},        {DIR_CW, 6, SW_DIVERGED, 0},        {DIR_CW, 6, SW_DIVERGED, 0},        {DIR_CCW, 4, SW_DIVERGED, 0},       {DIR_CCW, 4, SW_DIVERGED, 0}},
/* 18*/{{DIR_CW, 6, SW_DIVERGED, 0},         {DIR_CW, 6, SW_DIVERGED, 0},        {DIR_CW, 6, SW_DIVERGED, 0},        {DIR_CCW, 4, SW_DIVERGED, 0},       {DIR_CCW, 4, SW_DIVERGED, 0},       {DIR_CCW, 4, SW_DIVERGED, 0},       {DIR_CCW, 4, SW_DIVERGED, 0},       {DIR_CCW, 4, SW_DIVERGED, 0},       {DIR_CCW, 4, SW_DIVERGED, 0},       {DIR_CCW, 4, SW_DIVERGED, 0},       {DIR_CCW, 4, SW_DIVERGED, 0},       {DIR_CCW, 4, SW_DIVERGED, 0},       {DIR_CW, 6, SW_DIVERGED, 0},        {DIR_CW, 6, SW_DIVERGED, 0},        {DIR_CW, 6, SW_DIVERGED, 0},        {DIR_CW, 6, SW_DIVERGED, 0},        {DIR_CW, NO_SWITCH, NO_SWITCH, 0},  {DIR_CW, NO_SWITCH, NO_SWITCH, 1},  {DIR_CCW, 4, SW_DIVERGED, 0},       {DIR_CCW, 4, SW_DIVERGED, 0},       {DIR_CW, 6, SW_DIVERGED, 0},        {DIR_CW, 6, SW_DIVERGED, 0},        {DIR_CCW, 4, SW_DIVERGED, 0},       {DIR_CCW, 4, SW_DIVERGED, 0}},
/* 19*/{{DIR_CCW, 1, SW_DIVERGED, 0},        {DIR_CCW, 1, SW_DIVERGED, 0},       {DIR_CCW, 1, SW_DIVERGED, 0},       {DIR_CW, 3, SW_DIVERGED, 0},        {DIR_CW, 3, SW_DIVERGED, 0},        {DIR_CW, 3, SW_DIVERGED, 0},        {DIR_CW, 3, SW_DIVERGED, 0},        {DIR_CW, 3, SW_DIVERGED, 0},        {DIR_CW, 3, SW_DIVERGED, 0},        {DIR_CW, 3, SW_DIVERGED, 0},        {DIR_CW, 3, SW_DIVERGED, 0},        {DIR_CCW, 1, SW_DIVERGED, 0},       {DIR_CCW, 1, SW_DIVERGED, 0},       {DIR_CCW, 1, SW_DIVERGED, 0},       {DIR_CCW, 1, SW_DIVERGED, 0},       {DIR_CCW, 1, SW_DIVERGED, 0},       {DIR_CCW, 1, SW_DIVERGED, 0},       {DIR_CW, 3, SW_DIVERGED, 0},        {DIR_CW, NO_SWITCH, NO_SWITCH, 1},  {DIR_CCW, NO_SWITCH, NO_SWITCH, 0}, {DIR_CCW, 1, SW_DIVERGED, 0},       {DIR_CCW, 1, SW_DIVERGED, 0},       {DIR_CW, 3, SW_DIVERGED, 0},        {DIR_CW, 3, SW_DIVERGED, 0}},
/* 20*/{{DIR_CCW, 1, SW_DIVERGED, 0},        {DIR_CCW, 1, SW_DIVERGED, 0},       {DIR_CCW, 1, SW_DIVERGED, 0},       {DIR_CW, 3, SW_DIVERGED, 0},        {DIR_CW, 3, SW_DIVERGED, 0},        {DIR_CW, 3, SW_DIVERGED, 0},        {DIR_CW, 3, SW_DIVERGED, 0},        {DIR_CW, 3, SW_DIVERGED, 0},        {DIR_CW, 3, SW_DIVERGED, 0},        {DIR_CW, 3, SW_DIVERGED, 0},        {DIR_CW, 3, SW_DIVERGED, 0},        {DIR_CCW, 1, SW_DIVERGED, 0},       {DIR_CCW, 1, SW_DIVERGED, 0},       {DIR_CCW, 1, SW_DIVERGED, 0},       {DIR_CCW, 1, SW_DIVERGED, 0},       {DIR_CCW, 1, SW_DIVERGED, 0},       {DIR_CCW, 1, SW_DIVERGED, 0},       {DIR_CW, 3, SW_DIVERGED, 0},        {DIR_CW, NO_SWITCH, NO_SWITCH, 0},  {DIR_CW, NO_SWITCH, NO_SWITCH, 1},  {DIR_CCW, 1, SW_DIVERGED, 0},       {DIR_CCW, 1, SW_DIVERGED, 0},       {DIR_CW, 3, SW_DIVERGED, 0},        {DIR_CW, 3, SW_DIVERGED, 0}},
/* 21*/{{DIR_CW, 5, SW_DIVERGED, 0},         {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, NO_SWITCH, NO_SWITCH, 1},  {DIR_CCW, NO_SWITCH, NO_SWITCH, 0}, {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0}},
/* 22*/{{DIR_CW, 5, SW_DIVERGED, 0},         {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, NO_SWITCH, NO_SWITCH, 0},  {DIR_CW, NO_SWITCH, NO_SWITCH, 1},  {DIR_CW, 5, SW_DIVERGED, 0},        {DIR_CW, 5, SW_DIVERGED, 0}},
/* 23*/{{DIR_CW, 2, SW_DIVERGED, 0},         {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, NO_SWITCH, NO_SWITCH, 1},  {DIR_CCW, NO_SWITCH, NO_SWITCH, 0}},
/* 24*/{{DIR_CW, 2, SW_DIVERGED, 0},         {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, 2, SW_DIVERGED, 0},        {DIR_CW, NO_SWITCH, NO_SWITCH, 0},  {DIR_CW, NO_SWITCH, NO_SWITCH, 1}}
};

/*
 * @brief   Function used to obtain instructions on how to go from one
 *          hall sensor the the next on the train track
 * @param   [in] unsigned char start: Index of starting hall sensor
 * @param   [in] unsigned char finish: Index of ending hall sensor
 * @return  RoutingTableEntry: Instruction set for desired path
 */
inline struct RoutingTableEntry getPath(unsigned char start, unsigned char finish)
{
    return RoutingTable[start][finish];
}
